name: ElementalEffects
author: xNuminousx
version: 1.3
depend: [ProjectKorra]
main: com.xnuminousx.elementaleffects.Main
description: A plug-in full of different cosmetic effects for the different elements.

commands:
  ee:
    usage: /<command>
    aliases: elementaleffects
    description: Shows a list of commands for ElementalEffects.